sudo: required

language: java

jdk: oraclejdk8
env:
  global:
    - ER_VERSION: $(mvn -q \
                         -Dexec.executable="echo" \
                         -Dexec.args='${project.version}' \
                         --non-recursive \
                         org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)



jobs:
  include:
    - stage: test
      script:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
        - mvn clean verify
    - stage: staging
      if: branch = master
      script:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
        - mvn package
        - echo "Creating stage docker for ERBaseline version [${env.ER_VERSION}]"
        - docker build -f docker/Dockerfile -t stellar-erbaseline:RC_latest .
        - docker tag stellar-erbaseline::RC_latest data61/stellar-erbaseline:RC_$ER_VERSION
        - echo "Release a stage build."
        - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
        - docker push data61/stellar-erbaseline:latest
        - docker push data61/stellar-erbaseline:RC_${env.ER_VERSION}